import { GameConfig } from "@/interfaces/settings";

const gameConfig: GameConfig = {
  UID: "00000000",
  flightMode: false,
  UnlockSkin: true,
  PlayerSpeed: false,
  VacuumCollect: false,
  playerSpeedValue: 2,
  buffType: 0,
  GodMode: false,
  VacuumRadius: 300,
  Language: "English",
  FPSUnlocker: false,
  NoCD: false,
  KillAnimal: false,
  AutoPickTreasure: false,
  AutoAbsorb: false,
  AutoLoot: false,
  PerceptionRange: false,
  AutoSonanceCasket: false,
  HasCustomTpFile: false,
  AlwaysCrit: false,
  killAuraRadius: 15,
  Custom_Skills: 0,
  Custom_Skills_id: 300520,
  AutoDestroy: false,
  WorldSpeed: false,
  WorldSpeedValue: 2,
  ShowFPS: false,
  PlotSkip: false,
  AutoPuzzle: false,
  NoClip: false,
  killAura: false,
  InfiniteStamina: false,
  MobVacuum: false,
  HideDmgUi: false,
  MarkTp: false,
  MarkX: 0,
  MarkY: 0,
  MarkZ: 0,
  MarkTpPosZ: 300,
  QuestTp: false,
  AutoTpTrackedMonster: false,
  QuestX: 0,
  QuestY: 0,
  QuestZ: 0,
  WaypointsLongRange: false,
  IllusiveSprint: false,
  AntiDither: true,
  MaxResonanceChain: false,
  MaxWeaponRank: false,
  OneHitKill: false,
  MaterialShellBuff: false,
  EchoesBuff: false,
  SuperBuff: false,
  AutoLootDistance: 300,
  AutoTreasureDistance: 300,
  AutoAbsorbDistance: 300,
  HitMultiplier: false,
  Hitcount: 15,
  VehicleSpeed: false,
  TreasureTpOverlay: true,
};

export { gameConfig };
