import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidenav } from "../components/Sidenav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-dark text-white`}
      >
        <main className="container mx-auto w-4xl mt-5">
          {/* Header */}
          <div className="flex items-center py-5 border border-white/15 rounded">
            <h2 className="text-2xl font-bold mx-auto">Waves 2.1.2</h2>
          </div>
          <section className="border-l border-r border-b flex border-white/15 rounded">
            <Sidenav />
            <div className="flex-1">{children}</div>
          </section>
        </main>
      </body>
    </html>
  );
}
